version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CLIENT_ORIGIN=${CLIENT_ORIGIN:-*}
    depends_on:
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

